// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main.proto

#ifndef PROTOBUF_main_2eproto__INCLUDED
#define PROTOBUF_main_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_main_2eproto();
void protobuf_AssignDesc_main_2eproto();
void protobuf_ShutdownFile_main_2eproto();

class BaseNetworkable;

// ===================================================================

class BaseNetworkable : public ::google::protobuf::Message {
 public:
  BaseNetworkable();
  virtual ~BaseNetworkable();

  BaseNetworkable(const BaseNetworkable& from);

  inline BaseNetworkable& operator=(const BaseNetworkable& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BaseNetworkable& default_instance();

  void Swap(BaseNetworkable* other);

  // implements Message ----------------------------------------------

  BaseNetworkable* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BaseNetworkable& from);
  void MergeFrom(const BaseNetworkable& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 uid = 1;
  inline bool has_uid() const;
  inline void clear_uid();
  static const int kUidFieldNumber = 1;
  inline ::google::protobuf::uint32 uid() const;
  inline void set_uid(::google::protobuf::uint32 value);

  // required uint32 group = 2;
  inline bool has_group() const;
  inline void clear_group();
  static const int kGroupFieldNumber = 2;
  inline ::google::protobuf::uint32 group() const;
  inline void set_group(::google::protobuf::uint32 value);

  // required uint32 prefabID = 3;
  inline bool has_prefabid() const;
  inline void clear_prefabid();
  static const int kPrefabIDFieldNumber = 3;
  inline ::google::protobuf::uint32 prefabid() const;
  inline void set_prefabid(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:BaseNetworkable)
 private:
  inline void set_has_uid();
  inline void clear_has_uid();
  inline void set_has_group();
  inline void clear_has_group();
  inline void set_has_prefabid();
  inline void clear_has_prefabid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 uid_;
  ::google::protobuf::uint32 group_;
  ::google::protobuf::uint32 prefabid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_main_2eproto();
  friend void protobuf_AssignDesc_main_2eproto();
  friend void protobuf_ShutdownFile_main_2eproto();

  void InitAsDefaultInstance();
  static BaseNetworkable* default_instance_;
};
// ===================================================================


// ===================================================================

// BaseNetworkable

// required uint32 uid = 1;
inline bool BaseNetworkable::has_uid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BaseNetworkable::set_has_uid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BaseNetworkable::clear_has_uid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BaseNetworkable::clear_uid() {
  uid_ = 0u;
  clear_has_uid();
}
inline ::google::protobuf::uint32 BaseNetworkable::uid() const {
  return uid_;
}
inline void BaseNetworkable::set_uid(::google::protobuf::uint32 value) {
  set_has_uid();
  uid_ = value;
}

// required uint32 group = 2;
inline bool BaseNetworkable::has_group() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BaseNetworkable::set_has_group() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BaseNetworkable::clear_has_group() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BaseNetworkable::clear_group() {
  group_ = 0u;
  clear_has_group();
}
inline ::google::protobuf::uint32 BaseNetworkable::group() const {
  return group_;
}
inline void BaseNetworkable::set_group(::google::protobuf::uint32 value) {
  set_has_group();
  group_ = value;
}

// required uint32 prefabID = 3;
inline bool BaseNetworkable::has_prefabid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void BaseNetworkable::set_has_prefabid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void BaseNetworkable::clear_has_prefabid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void BaseNetworkable::clear_prefabid() {
  prefabid_ = 0u;
  clear_has_prefabid();
}
inline ::google::protobuf::uint32 BaseNetworkable::prefabid() const {
  return prefabid_;
}
inline void BaseNetworkable::set_prefabid(::google::protobuf::uint32 value) {
  set_has_prefabid();
  prefabid_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_main_2eproto__INCLUDED
